### PR TITLE
[euphoria-operator-testkit] Filter test.

### PR DESCRIPTION
**Pull request by dmvk**

### CODE REVIEW

**Comment by dmvk** [comment]
What should be expected behaviour, in case persist was not call? I'd say that its subtree should not be part of the result DAG.

**Comment by je-ik** [comment]
The expected behavior is quite undefined I suppose. It definitely should not fail. :)
I'm not sure it the operator should not be run at all, because it could have some side-effects. On the other hand, if it has side-effects, it can be persisted into `VoidSink` for instance. But it might seem a little weird to users.

**Comment by je-ik** [comment]
Do we still want to merge this?

**Comment by dmvk** [comment]
obsolete

**Pull request closed without merging**
